# Generated by Django 5.1.4 on 2024-12-12 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=200, verbose_name='Nome da Catergoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=250, verbose_name='id do fornecedor')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('codigo_produto', models.CharField(max_length=50, unique=True)),
                ('descricao_produto', models.TextField(blank=True, max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quant_estoque', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('Categoria', models.ManyToManyField(related_name='categorias', to='busca.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.fornecedor')),
            ],
        ),
    ]
