# Generated by Django 5.1.4 on 2024-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('codigo_produto', models.CharField(max_length=50, unique=True)),
                ('descricao_produto', models.TextField(blank=True, max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quant_estoque', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
